lsi: false
safe: true
source: .
title: "Dustin Dortch"
incremental: false
highlighter: rouge
gist:
  noscript: false
  noscript_message: "Gist embeds require JavaScript to view. Visit https://gist.github.com/your-gist-id to view this gist."
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge